# Generated by Django 5.1.4 on 2025-01-30 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
            ],
            options={
                'ordering': ('description',),
            },
        ),
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
