# Generated by Django 5.1.4 on 2025-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_transaction_delete_basemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
